[ejs.app]
title = "TROPIMON"

[ejs.landing]
mediaGitHubURL = "https://tropimon.fr"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/QZk6vU5A"

[ejs.settings]
sourceGithubLink = "https://github.com/Erusel/TropimonLauncher/"
supportLink = "https://discord.gg/QZk6vU5A"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Tropimon !"
welcomeDescription = "Notre mission est de réunir les fans de pokémon sur le meilleur serveur cobblemon au monde !"
welcomeDescCTA = "Vous n'etes a qu'a quelque clique de Tropimon !"
