[ejs.app]
title = "TROPIMON"

[ejs.landing]
mediaGitHubURL = "https://tropimon.fr"
mediaTwitterURL = "https://twitter.com/PlayTropimon"
mediaInstagramURL = "https://www.instagram.com/tropimon/"
mediaYouTubeURL = "https://www.youtube.com/channel/UCJKleMt81d4RPq-odOfBYDQ"
mediaDiscordURL = "https://discord.gg/QZk6vU5A"
mediaTikTokURL = "https://www.tiktok.com/@tropimon"

[ejs.settings]
sourceGithubLink = "https://github.com/Erusel/TropimonLauncher/"
supportLink = "https://discord.gg/QZk6vU5A"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Tropimon !"
welcomeDescription = "Notre mission est de réunir les fans de pokémon sur le meilleur serveur cobblemon au monde !"
welcomeDescCTA = "Vous n'etes a qu'a quelque clique de Tropimon !"
